3rdparty/llama.cpp/build-cuda-native/bin/llama-cli \
  --model models/Qwen-Qwen3-VL-2B-Instruct-gguf/Qwen-Qwen3-VL-2B-Instruct-f16.gguf \
  --mmproj models/Qwen-Qwen3-VL-2B-Instruct-gguf/mmproj-Qwen-Qwen3-VL-2B-Instruct-f16.gguf \
  --image test/data/example/pics_downsample/mnn_test.jpg \
  --file test/data/example/prompts/taobao.txt \
  --ctx-size 8192 \
  --n-gpu-layers 99 \
  --threads 16 \
  --temp 0 \
  --no-warmup \
  --single-turn \
  --simple-io 